# Generated by Django 3.2 on 2022-10-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=20)),
                ('razão', models.CharField(max_length=20)),
                ('insEst', models.CharField(max_length=20)),
                ('insMun', models.CharField(max_length=20)),
            ],
        ),
    ]
